In [1]:
import pandas as pd
import numpy as np


pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

In [7]:
df = pd.read_csv("clean_students.csv")

df.head()

      name  score grade
0    Aarav   88.0     B
1     Sita   76.0     B
2   Bikash   76.0     B
3    Kiran   91.0     A
4  Unknown   67.0     C

In [8]:
df = pd.read_csv("clean_students.csv")

df.head()

      name  score grade
0    Aarav   88.0     B
1     Sita   76.0     B
2   Bikash   76.0     B
3    Kiran   91.0     A
4  Unknown   67.0     C

In [9]:
# Quick sanity checks
print(df.info())
print("\nMissing values:\n", df.isnull().sum())

# Ensure score is numeric
df["score"] = pd.to_numeric(df["score"], errors="coerce")

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    14 non-null     str
 1   score   14 non-null     float64
 2   grade   14 non-null     str
dtypes: float64(1), str(2)
memory usage: 468.0 bytes
None

Missing values:
 name     0
score    0
grade    0
dtype: int64

In [10]:
def assign_grade(score):
    if score >= 90:
        return "A"
    elif score >= 75:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "F"

In [11]:
df["grade"] = df["score"].apply(assign_grade)

df[["score", "grade"]].head()

   score grade
0   88.0     B
1   76.0     B
2   76.0     B
3   91.0     A
4   67.0     C

In [12]:
df["passed"] = df["score"] >= 50

df[["score", "passed"]].head()

   score  passed
0   88.0    True
1   76.0    True
2   76.0    True
3   91.0    True
4   67.0    True

In [13]:
def score_category(score):
    if score >= 80:
        return "High"
    elif score >= 50:
        return "Medium"
    else:
        return "Low"

df["score_category"] = df["score"].apply(score_category)

df[["score", "score_category"]].head()

   score score_category
0   88.0           High
1   76.0         Medium
2   76.0         Medium
3   91.0           High
4   67.0         Medium

In [14]:
df["rank"] = df["score"].rank(ascending=False, method="dense").astype(int)

df.sort_values("rank").head()

     name  score grade  passed score_category  rank
10  Rekha   95.0     A    True           High     1
3   Kiran   91.0     A    True           High     2
0   Aarav   88.0     B    True           High     3
9   Gopal   83.0     B    True           High     4
1    Sita   76.0     B    True         Medium     5

In [15]:
grade_stats = df.groupby("grade")["score"].agg(
    count="count",
    mean="mean",
    min="min",
    max="max"
).reset_index()

grade_stats

  grade  count       mean   min   max
0     A      2  93.000000  91.0  95.0
1     B      5  79.800000  76.0  88.0
2     C      3  67.666667  64.0  72.0
3     D      1  59.000000  59.0  59.0
4     F      3  28.000000   0.0  45.0

In [16]:
df = df.sort_values("rank").reset_index(drop=True)

df.head(10)

      name  score grade  passed score_category  rank
0    Rekha   95.0     A    True           High     1
1    Kiran   91.0     A    True           High     2
2    Aarav   88.0     B    True           High     3
3    Gopal   83.0     B    True           High     4
4     Sita   76.0     B    True         Medium     5
5   Sunita   76.0     B    True         Medium     5
6   Bikash   76.0     B    True         Medium     5
7    Bibek   72.0     C    True         Medium     6
8  Unknown   67.0     C    True         Medium     7
9   Kabita   64.0     C    True         Medium     8

In [17]:
df.to_csv("enriched_students.csv", index=False)

print("File saved: enriched_students.csv")

File saved: enriched_students.csv

In [18]:
df.head(5)

    name  score grade  passed score_category  rank
0  Rekha   95.0     A    True           High     1
1  Kiran   91.0     A    True           High     2
2  Aarav   88.0     B    True           High     3
3  Gopal   83.0     B    True           High     4
4   Sita   76.0     B    True         Medium     5