In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

# Creating messy Nepali-style student dataset manually

data = {
    "name": [" Aarav ", "sita", "BIKASH", "priya ", "Kiran", None,
             " anjali", "ROSHAN", "Mina ", "suman", "Aarav",
             "  bibek ", "NISHA", "gopal", "Rekha ", "sunita",
             "KABITA", "ram ", "Hari", "  sita "],

    "score": ["88", " 76 ", None, "-12", "91", "67",
              "45", "101", "59", "0", "88",
              " 72", "-5", "83", "95 ", None,
              "64", "39", "110", "76"]
}

# Create DataFrame
df_messy = pd.DataFrame(data)

# Add duplicate rows deliberately
df_messy = pd.concat([df_messy, df_messy.iloc[[1, 4, 10]]], ignore_index=True)

# Save to CSV
df_messy.to_csv("messy_students.csv", index=False)

print("messy_students.csv created successfully!")
print(df_messy)

messy_students.csv created successfully!
        name score
0     Aarav     88
1       sita   76
2     BIKASH   NaN
3     priya    -12
4      Kiran    91
5        NaN    67
6     anjali    45
7     ROSHAN   101
8      Mina     59
9      suman     0
10     Aarav    88
11    bibek     72
12     NISHA    -5
13     gopal    83
14    Rekha    95
15    sunita   NaN
16    KABITA    64
17      ram     39
18      Hari   110
19     sita     76
20      sita   76
21     Kiran    91
22     Aarav    88

In [3]:
# Load messy dataset

df = pd.read_csv("messy_students.csv")

print("Dataset Loaded Successfully!\n")

df.head(10)

Dataset Loaded Successfully!

      name  score
0   Aarav    88.0
1     sita   76.0
2   BIKASH    NaN
3   priya   -12.0
4    Kiran   91.0
5      NaN   67.0
6   anjali   45.0
7   ROSHAN  101.0
8    Mina    59.0
9    suman    0.0

In [8]:
# Basic information about dataset

print("====DATAFRAME INFO====" )
print(df.info())

print("\n===== NULL VALUES =====")
print(df.isnull().sum())

====DATAFRAME INFO====
<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    22 non-null     str
 1   score   21 non-null     float64
dtypes: float64(1), str(1)
memory usage: 500.0 bytes
None

===== NULL VALUES =====
name     1
score    2
dtype: int64

In [9]:
# Find duplicate rows

duplicates = df[df.duplicated()]

print("===== DUPLICATE ROWS =====")
print(duplicates)

print(f"\nTotal Duplicate Rows: {df.duplicated().sum()}")

===== DUPLICATE ROWS =====
     name  score
20   sita   76.0
21  Kiran   91.0
22  Aarav   88.0

Total Duplicate Rows: 3

In [11]:
# Store original row count before cleaning

before_rows = df.shape[0]

print(f"Rows Before Cleaning: {before_rows}")

Rows Before Cleaning: 23

In [ ]:
# Remove extra spaces from names

df["name"] = df["name"].str.strip()

print("Whitespace cleaned ssouccessfully!")

Whitespace cleaned successfully!

In [13]:
# Convert names to proper title case

df["name"] = df["name"].str.title()

print("Name casing standardized!")

Name casing standardized!

In [14]:
# Convert score column to numeric

df["score"] = pd.to_numeric(df["score"], errors="coerce")

print(df.dtypes)

name         str
score    float64
dtype: object

In [ ]:
# Fill missing names with 'Unknown'
df["name"] = df["name"].fillna("Unknown")

# Fill missing scores with median score
median_score = df["score"].median()

df["score"] = df["score"].fillna(median_score)

print("Missing values handled successfully!")

Missing values handled successfully!

In [16]:
# Remove rows where score is below 0 or above 100

df = df[(df["score"] >= 0) & (df["score"] <= 100)]

print("Invalid scores removed!")

Invalid scores removed!

In [17]:
# Remove duplicate rows

df = df.drop_duplicates()

print("Duplicate rows removed!")

Duplicate rows removed!

In [18]:
# Function to assign grades

def assign_grade(score):
    
    if score >= 90:
        return "A"
    
    elif score >= 75:
        return "B"
    
    elif score >= 50:
        return "C"
    
    else:
        return "F"


# Create grade column
df["grade"] = df["score"].apply(assign_grade)

print("Grade column added successfully!")

Grade column added successfully!

In [19]:
print("===== CLEANED DATASET =====")

df

===== CLEANED DATASET =====

       name  score grade
0     Aarav   88.0     B
1      Sita   76.0     B
2    Bikash   76.0     B
4     Kiran   91.0     A
5   Unknown   67.0     C
6    Anjali   45.0     F
8      Mina   59.0     C
9     Suman    0.0     F
11    Bibek   72.0     C
13    Gopal   83.0     B
14    Rekha   95.0     A
15   Sunita   76.0     B
16   Kabita   64.0     C
17      Ram   39.0     F

In [20]:
# Save cleaned data to CSV

df.to_csv("clean_students.csv", index=False)

print("clean_students.csv saved successfully!")

clean_students.csv saved successfully!

In [21]:
after_rows = df.shape[0]

print("===== ROW COUNT COMPARISON =====")

print(f"Rows Before Cleaning : {before_rows}")
print(f"Rows After Cleaning  : {after_rows}")
print(f"Rows Removed         : {before_rows - after_rows}")

===== ROW COUNT COMPARISON =====
Rows Before Cleaning : 23
Rows After Cleaning  : 14
Rows Removed         : 9